def kostol():
    return {
        "Meno budovy": "Kostol sv. Štefana",
        "Adresa": "M. Kočanovej 1, Kostoľany nad Hornádom, Košice",
        "GPS súradnice": "NIE JE",
        "Rok výstavby": "pred rokom 1383",
        "Aktuálny vlastník": "Rímsko-katolícka cirkev, Kostoľany nad Hornádom",
        "Rok zaradenia": "NIE JE",
        "Historický význam": "NIE JE",
        "Záznamy o obnove": "1774 - prestavba kostola v rokokovom štýle, 1891 - interiér kostola doplnený o nový oltár, 1929 - premaľovaný, 1950 - odstránený hlavný oltár a nanovo premaľované fasády nevhodným brizolitovým nástrekom, 1990 - nad hlavným vstupom ukotvený kovový kryt s presklením, v súčastnosti 2008 prebieho obnova strešnej krytiny",
        "Materiál vonkajšej fasády": "brizolitový nástrek",
        "Typ strechy": "Sedlová",
        "Materiál interiéru": "Tehlové klenby, drevený krov, omietané steny, drevo, podlaha krytá keramickou dlažbou",
        "Iné materiály": "NIE JE",
        "Aktuálny stav": "dobrý",
        "Kritické miesta": "NIE JE",
        "Potrebné sanácie": "NIE JE",
        "Súčasné fotografie": "Mgr. Kamil Alezár digitálne fotografie, pohľad do priestoru, pohľad do schodiska, pohľad na víťazný oblúk lode z juhu, detail rímsovej hlavice lode kostola, čelný pohľad na kostol z juhu",
        "Historické fotografie": "NIE JE",
        "Plány a schémy": "NIE JE",
        "Harmonogram údržby": "NIE JE",
        "Revízne záznamy": "NIE JE",
        "Ochranné zóny": "NIE JE",
        "Povolenia na zásahy": "NIE JE",
        "Legislatívne obmedzenia": "všeobecne platné legislatívne obmedzenia o ochrane pamiatkového fondu",
        "Digitálne výkresy": "NIE JE",
        "Archeologické výskumy": "Kostol a jeho okolie doteraz neboli predmetom archeologockého výskumu",
        "Chemické analýzy": "NIE JE",
    }

def mestiansky_dom():
    return {
        "Meno budovy": "Dom meštiansky",
        "Adresa": "Hlavná 90/48, Košice",
        "GPS súradnice": "NIE JE",
        "Rok výstavby": "NIE JE",
        "Aktuálny vlastník": "NIE JE",
        "Rok zaradenia": "NIE JE",
        "Historický význam": "NIE JE",
        "Záznamy o obnove": "1556 - spojenie dvoch domov a zalícovanie fasád, 1600 - prestavba, v pol. 18. stor. - premiestnenie schodiska zhruba do súčasnej polohy a vznik podkrovia; v 70-tych rokoch 19. stor. - úprava schodiska, prefasádovanie uličného priečelia, úprava podkrovia na bývanie; v 20. stor. niekoľko utilitárnych zásahov narušujúcich pamiatkovú hodnotu.",
        "Materiál vonkajšej fasády": "Režné tehlové murivo.",
        "Typ strechy": "nad hlavným krídlom sedlová so spádom do ulice, kombinovaná s 2 sedlovými priečnymi strechami; dvorové krídlo pultová strecha",
        "Materiál interiéru": "rovné stropy drevené trámové s omietaným rovným podhľadom; schodisko (konštrukcia žel.-betónová, stupne z umelého kameňa); suterénne podlahy hlinené",
        "Iné materiály": "suterén z kamenného muriva s neskoršími tehlovými plentami; vyššie úrovne s prevahou tehlového muriva; klenby kamenné a tehlové; krov drevený (kombinovaný); liatinové zábradlie hlavného schodiska; železné prútové zábradlia balkónov",
        "Aktuálny stav": "NIE JE",
        "Kritické miesta": "NIE JE",
        "Potrebné sanácie": "NIE JE",
        "Súčasné fotografie": "NIE JE",
        "Historické fotografie": "NIE JE",
        "Plány a schémy": "NIE JE",
        "Harmonogram údržby": "NIE JE",
        "Revízne záznamy": "NIE JE",
        "Ochranné zóny": "NIE JE",
        "Povolenia na zásahy": "NIE JE",
        "Legislatívne obmedzenia": "NIE JE",
        "Digitálne výkresy": "NIE JE",
        "Archeologické výskumy": "NIE JE",
        "Chemické analýzy": "NIE JE",
    }

#subor Vodná 8.docx
def mestiansky_dom_2():
    return {
        "Meno budovy": "Dom meštiansky",
        "Adresa": "Vodná 8/943, Košice",
        "GPS súradnice": "NIE JE",
        "Rok výstavby": "pravdepodobne niekedy na začiatku 20.stor.",
        "Aktuálny vlastník": "NIE JE",
        "Rok zaradenia": "NIE JE",
        "Historický význam": "Doklad architektonickej, urbanistickej a stavebnej vývojovej etapy v rozvoji Košíc (koniec 19.stor. a začiatok 20.stor.) so silným secesným výrazom; vo vzťahu k stredovekému mestskému opevňovaciemu systému.",
        "Záznamy o obnove": "NIE JE",
        "Materiál vonkajšej fasády": "pôvodné omietkové vrstvy s farebným riešením; štukatérske práce na fasádach",
        "Typ strechy": "uličné krídlo sedlová strecha; dvorové krídla pultové strechy (novotvary) + priebežný strešný vikier",
        "Materiál interiéru": "drevo (trámové stropy, stolárske výrobky, kazetové dvere, vlyskové podlahy), omietky (na rákos), keramické podlahy, kameninové schody, kované zábradlia",
        "Iné materiály": "plná pálená tehla (murovaná technológia), oceľové traverzy (suterén), železobetónový strop (novodobý), ľahké transparentné zastrešenie dvora",
        "Aktuálny stav": "po obnove",
        "Kritické miesta": "NIE JE",
        "Potrebné sanácie": "NIE JE",
        "Súčasné fotografie": "Mgr. Juraj Gembický, KPÚ Košice, december 2001",
        "Historické fotografie": "NIE JE",
        "Plány a schémy": "NIE JE",
        "Harmonogram údržby": "NIE JE",
        "Revízne záznamy": "NIE JE",
        "Ochranné zóny": "NIE JE",
        "Povolenia na zásahy": "NIE JE",
        "Legislatívne obmedzenia": "NIE JE",
        "Digitálne výkresy": "NIE JE",
        "Archeologické výskumy": "predmetom ochrany sú archeologické nálezy/kultúrne vrstvy pod terénom.",
        "Chemické analýzy": "NIE JE",
    }

def synagoga():
    return {
        "Meno budovy": "Synagóga",
        "Adresa": "Zvonárska ulica, Košice",
        "GPS súradnice": "NIE JE",
        "Rok výstavby": "1883 (prestavba), pôvodná stavba 1842",
        "Aktuálny vlastník": "NIE JE",
        "Rok zaradenia": "NIE JE",
        "Historický význam": "Národná kultúrna pamiatka",
        "Záznamy o obnove": "1881, 1904, 1999–2000 čiastočné opravy, poškodenie interiéru a fasády",
        "Materiál vonkajšej fasády": "Omietka, hladká, monochromatická (žltý oker), riadkovaná",
        "Typ strechy": "Sedlová strecha s plechovou krytinou",
        "Materiál interiéru": "Drevené konštrukcie, omietnuté steny, dekoratívne maľby, kovové stĺpy, drevené a sklenené výplne",
        "Iné materiály": "Liatinové stĺpy, keramitová dlažba, kovové mreže, rezbárske prvky",
        "Aktuálny stav": "Synagóga je v súčasnosti v zdevastovanom stave, pričom celá skladba podlahy chýba a v interiéri je rastlý terén.",
        "Kritické miesta": "Poškodené omietky, chýbajúce podlahy, poškodené okenné výplne, degradované drevené konštrukci",
        "Potrebné sanácie": "NIE JE",
        "Súčasné fotografie": "NIE JE",
        "Historické fotografie": "NIE JE",
        "Plány a schémy": "NIE JE",
        "Harmonogram údržby": "NIE JE",
        "Revízne záznamy": "NIE JE",
        "Ochranné zóny": "Mestskej pamiatkovej rezervácii (MPR) Košice",
        "Povolenia na zásahy": "NIE JE",
        "Legislatívne obmedzenia": "pamiatkový zákon, potreba zachovania základnej architektonickej hmoty, umelecko-remeselných prvkov a dispozície na všetkých podlažiach",
        "Digitálne výkresy": "NIE JE",
        "Archeologické výskumy": "Neboli realizované",
        "Chemické analýzy": "NIE JE",
    }

def kastiel():
    return {
        "Meno budovy": "Kaštieľ Semseyovcov",
        "Adresa": "Šemšanská ulica, Košice-Šaca",
        "GPS súradnice": "NIE JE",
        "Rok výstavby": "1776",
        "Aktuálny vlastník": "NIE JE",
        "Rok zaradenia": "NIE JE",
        "Historický význam": "Národná kultúrna pamiatka (ÚZKP 4127/0), barokový kaštieľ s prvkami klasicizmu",
        "Záznamy o obnove": "NIE JE.",
        "Materiál vonkajšej fasády": "NIE JE",
        "Typ strechy": "manzardová strecha s plechovou krytinou",
        "Materiál interiéru": "tehlové klenby, drevené výplne, linoleum, hlina (suterén)",
        "Iné materiály": "drevený krov, pozinkovaný plech, betónové schodiská",
        "Aktuálny stav": "zachovaná hmotová skladba, poškodený interiér, chýbajúce pôvodné pece a mobiliár",
        "Kritické miesta": "NIE JE",
        "Potrebné sanácie": "NIE JE",
        "Súčasné fotografie": "NIE JE",
        "Historické fotografie": "NIE JE",
        "Plány a schémy": "NIE JE",
        "Harmonogram údržby": "NIE JE",
        "Revízne záznamy": "NIE JE",
        "Ochranné zóny": "NIE JE",
        "Povolenia na zásahy": "NIE JE",
        "Legislatívne obmedzenia": "ochrana architektonických, výtvarných a remeselných prvkov, dispozičného riešenia a hmoty objektu",
        "Digitálne výkresy": "NIE JE",
        "Archeologické výskumy": "NIE JE",
        "Chemické analýzy": "NIE JE",
    }